export const HOURS_ON_GET_ALL_REQUESTED = 'HOURS_ON_GET_ALL_REQUESTED';
export const HOURS_ON_GET_ALL_SUCCEEDED = 'HOURS_ON_GET_ALL_SUCCEEDED';
export const HOURS_ON_GET_ALL_FAILED = 'HOURS_ON_GET_ALL_FAILED';
