export const HOURS_ON_GET_REQUESTED = 'HOURS_ON_GET_REQUESTED';
export const HOURS_ON_GET_SUCCEEDED = 'HOURS_ON_GET_SUCCEEDED';
export const HOURS_ON_GET_FAILED = 'HOURS_ON_GET_FAILED';

export const HOURS_ON_CREATE_REQUESTED = 'HOURS_ON_CREATE_REQUESTED';
export const HOURS_ON_CREATE_SUCCEEDED = 'HOURS_ON_CREATE_SUCCEEDED';
export const HOURS_ON_CREATE_FAILED = 'HOURS_ON_CREATE_FAILED';
