export const PROYECTS_ON_GET_ALL_REQUESTED = 'PROYECTS_ON_GET_ALL_REQUESTED';
export const PROYECTS_ON_GET_ALL_SUCCEEDED = 'PROYECTS_ON_GET_ALL_SUCCEEDED';
export const PROYECTS_ON_GET_ALL_FAILED = 'PROYECTS_ON_GET_ALL_FAILED';

export const PROYECTS_ON_CREATE_REQUESTED = 'PROYECTS_ON_CREATE_REQUESTED';
export const PROYECTS_ON_CREATE_SUCCEEDED = 'PROYECTS_ON_CREATE_SUCCEEDED';
export const PROYECTS_ON_CREATE_FAILED = 'PROYECTS_ON_CREATE_FAILED';