export const TICKETS_ON_GET_ALL_REQUESTED = 'TICKETS_ON_GET_ALL_REQUESTED';
export const TICKETS_ON_GET_ALL_SUCCEEDED = 'TICKETS_ON_GET_ALL_SUCCEEDED';
export const TICKETS_ON_GET_ALL_FAILED = 'TICKETS_ON_GET_ALL_FAILED';
